[package]
name = "xsum"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = { version = "0.6.0", features = ["html_reports"] }

[profile.release]
lto = true
codegen-units = 1
strip = true

[[bench]]
name = "bench_xsum_sum"
harness = false
